import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/AuthContext/AuthContext";
import { BlogProvider } from "@/context/BlogContext/BlogContext";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/lib/react-query";
import localFont from "next/font/local";
import FooterLayout from "@/components/Footer/FooterComponent";

export const metadata: Metadata = {
  title: "Neves Jr",
  description: "Generated by create next app",
};

export const monumentFontFamily = localFont({
  src: "../../public/fonts/MonumentExtended-Regular.otf",
  variable: "--font-monument",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={monumentFontFamily.variable}>
      <AuthProvider>
        <BlogProvider>
          <QueryClientProvider client={queryClient}>
            <body>
              <Navbar />
              {children}
              <FooterLayout />
              <ToastContainer />
            </body>
          </QueryClientProvider>
        </BlogProvider>
      </AuthProvider>
    </html>
  );
}
