import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/src/context/AuthContext/AuthContext";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/src/lib/react-query";
import localFont from "next/font/local";
import FooterLayout from "@/components/Footer/FooterComponent";
import {
  AbstractIntlMessages,
  hasLocale,
  NextIntlClientProvider,
} from "next-intl";
import { Locale, routing } from "@/src/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import "react-international-phone/style.css";

export const metadata: Metadata = {
  title: "Neves Jr",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "../favicon.ico" }],
  },
};

export const monumentFontFamily = localFont({
  src: "../../../public/fonts/MonumentExtended-Regular.otf",
  variable: "--font-monument",
});

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages: AbstractIntlMessages = await getMessages();
  if (!hasLocale(routing.locales, locale as Locale)) {
    notFound();
  }

  return (
    <html lang={locale} className={monumentFontFamily.variable}>
      <head>
        <link
          rel="shortcut icon"
          href="nevesjrFavicon.ico"
          type="image/x-icon"
        />
      </head>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AuthProvider>
            <QueryClientProvider client={queryClient}>
              <Navbar />
              {children}
              <FooterLayout />
            </QueryClientProvider>
          </AuthProvider>
          <ToastContainer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
